# -*- coding: utf-8 -*-
"""siddhant-shendge_-invoice_data_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Sid3839/9c444467c454e6058a2b6e02883109ab/siddhant-shendge_-invoice_data_extraction.ipynb

# 0. Downloading Dependencies
"""

!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U safetensors
!pip install -q -U torch
!pip install -q -U xformers
!pip install -q -U langchain
!pip install -q -U ctransformers[cuda]
!pip install sentence-transformers
!pip -qqq install bitsandbytes accelerate

import os
os.kill(os.getpid(), 9)

"""# FIRST WAIT TILL THESE TWO CELLS ARE EXECUTED AND THEN RUN ALL THE NEXY CELLS"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/IDEA-Research/GroundingDINO.git
# %cd GroundingDINO
!pip install -e .

# Commented out IPython magic to ensure Python compatibility.
# %mkdir weights
# %cd weights
!wget -q https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth
# %cd ..

import subprocess

# Set locale to UTF-8
subprocess.run('export LC_ALL=C.UTF-8', shell=True)
subprocess.run('export LANG=C.UTF-8', shell=True)

# Install the package
subprocess.run('pip install git+https://github.com/facebookresearch/segment-anything.git', shell=True)

import locale
locale.getpreferredencoding = lambda: "UTF-8"

# Commented out IPython magic to ensure Python compatibility.
!git clone https://huggingface.co/spaces/abhishek/StableSAM/
!mkdir -p /content/GroundingDINO/checkpoints/
# %mv /content/GroundingDINO/StableSAM/sam_vit_h_4b8939.pth /content/GroundingDINO/checkpoints/sam_vit_h_4b8939.pth

!pip install pytesseract
!sudo apt-get install tesseract-ocr

!pip install gradio
!pip install PyMuPDF

"""## Downloading Receipt image"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/GroundingDINO

import requests
import os

# URL of the image
image_url = "https://expensesreceipt.com/assets/img/create-a-petrol-pump-receipt-by-customizing-template-for-India-customers.png?ver=1.231"

# Desired file path
file_path = "/content/GroundingDINO/data/receipt.jpg"

# Send a GET request to the URL
response = requests.get(image_url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Ensure that the directory exists
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    # Write the content of the response to the desired file path
    with open(file_path, "wb") as f:
        f.write(response.content)
    print("Image downloaded successfully and saved at:", file_path)
else:
    print("Failed to download image")

import os
from groundingdino.util.inference import load_model, load_image, predict, annotate
import supervision as sv
import torch
import numpy as np
import torch
from segment_anything import SamPredictor, sam_model_registry
import cv2
import matplotlib.pyplot as plt
import pytesseract
import re
from PIL import Image
from pytesseract import Output
import gradio as gr
import os

"""# 1. Detecting receipt in image"""

def process_image_with_model(image_path, text_prompt='receipt', box_threshold=0.35, text_threshold=0.25):
    HOME = os.getcwd()
    CONFIG = os.path.join('/content/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py')
    WEIGHTS_NAME = 'groundingdino_swint_ogc.pth'
    WEIGHTS_PATH = os.path.join('weights', WEIGHTS_NAME)

    model = load_model(CONFIG, WEIGHTS_PATH)
    image_source, image = load_image(image_path)

    boxes, logits, phrases = predict(
        model=model,
        image=image,
        caption=text_prompt,
        box_threshold=box_threshold,
        text_threshold=text_threshold
    )

    annotated_frame = annotate(
        image_source=image_source,
        boxes=boxes,
        logits=logits,
        phrases=phrases
    )
    cv2.imwrite('annotated_frame.jpg', annotated_frame)
    sv.plot_image(annotated_frame)

    return image_source, image, boxes, logits, phrases, annotated_frame, model

# Example usage:
IMAGE_PATH = os.path.join(os.getcwd(), 'data', 'receipt.jpg')
image_source, image, boxes, logits, phrases, annotated_frame, model = process_image_with_model(IMAGE_PATH)

"""# 2. Generate receipt mask"""

def process_image_with_sam(image_path,  model, box_threshold=0.35, text_threshold=0.25, text_prompt='receipt', model_type='vit_h', sam_checkpoint_path=None):
    image_source, image = load_image(image_path)
    h, w, _ = image_source.shape

    boxes, logits, phrases = predict(
        model=model,
        image=image,
        caption=text_prompt,
        box_threshold=box_threshold,
        text_threshold=text_threshold
    )

    box = boxes[0] * torch.Tensor([w, h, w, h])
    box[:2] -= box[2:] / 2
    box[2:] += box[:2]
    x0, y0, x1, y1 = box.int().tolist()
    input_box = np.array([x0,y0,x1,y1])
    input_point = None
    input_label = None

    img = image_source

    if sam_checkpoint_path is None:
        SAM_CHECKPOINT_PATH = os.path.join(os.getcwd(), 'checkpoints/sam_vit_h_4b8939.pth')
    else:
        SAM_CHECKPOINT_PATH = sam_checkpoint_path

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    sam = sam_model_registry[model_type](checkpoint=SAM_CHECKPOINT_PATH).to(device=device)

    predictor = SamPredictor(sam)
    predictor.set_image(img)

    masks, scores, _ = predictor.predict(
        point_coords=None,
        point_labels=None,
        box=input_box,
        multimask_output=False
    )

    sv.plot_image(masks[0])

    return masks, img

# Example usage:
IMAGE_PATH = os.path.join(os.getcwd(), 'data', 'receipt.jpg')
masks, img = process_image_with_sam(IMAGE_PATH, model)

"""# 3. Segment receipt from image"""

import cv2

def post_process_segmentation(masks, original_image):
    mask = np.expand_dims(masks[0], axis=0)
    mask = mask.transpose(1,2,0)
    mask = np.array(mask*255).astype('uint8')
    mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)

    segmented_image = mask
    segmented_image = cv2.bitwise_or(segmented_image, mask)

    segmented_image = cv2.bitwise_and(segmented_image, original_image)

    segmented_image_gray = cv2.cvtColor(segmented_image, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(segmented_image_gray, 127, 255, 0)

    sv.plot_image(thresh)

    # Save the thresholded image
    cv2.imwrite('segmented_image.jpg', thresh)

    return thresh

# Example usage:
thresh = post_process_segmentation(masks, img)

"""# 4. Top-down perspective transform of image"""

from skimage.filters import threshold_local
from PIL import Image

def opencv_resize(image, ratio):
    width = int(image.shape[1] * ratio)
    height = int(image.shape[0] * ratio)
    dim = (width, height)
    return cv2.resize(image, dim, interpolation = cv2.INTER_AREA)

def approximate_contour(contour):
    peri = cv2.arcLength(contour, True)
    return cv2.approxPolyDP(contour, 0.032 * peri, True)

def get_receipt_contour(contours):
    for c in contours:
        approx = approximate_contour(c)
        if len(approx) == 4:
            return approx

def wrap_perspective(img, rect):
    (tl, tr, br, bl) = rect

    maxWidth = max(int(np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))),
                   int(np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))))
    maxHeight = max(int(np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))),
                    int(np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))))

    dst = np.array([
        [0, 0],
        [maxWidth - 1, 0],
        [maxWidth - 1, maxHeight - 1],
        [0, maxHeight - 1]], dtype="float32")

    M = cv2.getPerspectiveTransform(np.array([tl, tr, br, bl], dtype="float32"), dst)

    warped = cv2.warpPerspective(img, M, (maxWidth, maxHeight))

    return warped


def contour_to_rect(contour):
    pts = contour.reshape(4, 2)
    rect = np.zeros((4, 2), dtype="float32")

    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]
    rect[2] = pts[np.argmax(s)]
    diff = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(diff)]
    rect[3] = pts[np.argmax(diff)]

    return rect

def bw_scanner(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    T = threshold_local(gray, 21, offset = 5, method = "gaussian")
    return (gray > T).astype("uint8") * 255


image = cv2.imread("segmented_image.jpg")
resize_ratio = 500 / image.shape[0]
original = image.copy()
image = opencv_resize(image, resize_ratio)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

img_with_contours = cv2.drawContours(img.copy(), contours, -1, (0, 255, 0), 3)

largest_contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]

receipt_contour = get_receipt_contour(largest_contours)

image_with_receipt_contour = cv2.drawContours(img.copy(), [receipt_contour], -1, (0, 255, 0), 2)

scanned = wrap_perspective(img.copy(), contour_to_rect(receipt_contour))

scanned_bw = bw_scanner(scanned)
sv.plot_image(scanned_bw)
cv2.imwrite('scanned.jpg', scanned_bw)

"""# 5. Apply OCR to obtain receipt content"""

import cv2
import matplotlib.pyplot as plt
import pytesseract
from pytesseract import Output

def plot_gray(image):
    plt.figure(figsize=(16,10))
    return plt.imshow(image, cmap='Greys_r')

def plot_rgb(image):
    plt.figure(figsize=(16,10))
    return plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

def process_image_and_extract_text(file_name):
    image = cv2.imread(file_name)
    plot_gray(image)

    d = pytesseract.image_to_data(image, output_type=Output.DICT)
    n_boxes = len(d['level'])
    boxes = cv2.cvtColor(image.copy(), cv2.COLOR_BGR2RGB)
    for i in range(n_boxes):
        (x, y, w, h) = (d['left'][i], d['top'][i], d['width'][i], d['height'][i])
        boxes = cv2.rectangle(boxes, (x, y), (x + w, y + h), (0, 255, 0), 2)

    plot_rgb(boxes)

    extracted_text = pytesseract.image_to_string(image)

    # Save the image with detected text boxes
    cv2.imwrite('boxes_image.jpg', cv2.cvtColor(boxes, cv2.COLOR_RGB2BGR))

    return extracted_text

# Example usage:
process_image_and_extract_text("scanned.jpg")

"""# Entire Pipeline (i.e Custon Function)"""

IMAGE_PATH = os.path.join(os.getcwd(), 'data', 'receipt.jpg')

def process_receipt_image(image_path):

    image_source, image, boxes, logits, phrases, annotated_frame, model = process_image_with_model(image_path)

    masks, img = process_image_with_sam(image_path, model)

    thresh = post_process_segmentation(masks, img)

    contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    img_with_contours = cv2.drawContours(img.copy(), contours, -1, (0, 255, 0), 3)

    largest_contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]

    receipt_contour = get_receipt_contour(largest_contours)

    image_with_receipt_contour = cv2.drawContours(img.copy(), [receipt_contour], -1, (0, 255, 0), 2)

    scanned = wrap_perspective(img.copy(), contour_to_rect(receipt_contour))

    scanned_bw = bw_scanner(scanned)
    sv.plot_image(scanned_bw)
    cv2.imwrite('scanned.jpg', scanned_bw)

    extracted_text = process_image_and_extract_text("scanned.jpg")

    return extracted_text

print(process_receipt_image(IMAGE_PATH))

"""# LLM Jsonifying"""

import torch
from transformers import BitsAndBytesConfig
from langchain.llms.huggingface_pipeline import HuggingFacePipeline
from langchain import PromptTemplate, LLMChain

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)
model_id = "mistralai/Mistral-7B-Instruct-v0.1"

model_4bit = AutoModelForCausalLM.from_pretrained( model_id,
                                                  device_map="auto",
                                                   quantization_config=quantization_config, )
tokenizer = AutoTokenizer.from_pretrained(model_id)

pipeline = pipeline(
        "text-generation",
        model=model_4bit,
        tokenizer=tokenizer,
        use_cache=True,
        device_map="auto",
        max_length=2000,
        truncation=True,
        do_sample=True,
        top_k=5,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
)

def generate_response(question, context):
    template = f"""<s>[INST] You are a helpful, respectful and honest assistant. Answer exactly in few words from the context
    Answer the question below from context below :
    {context}
    {question} [/INST] </s>
    """
    llm = HuggingFacePipeline(pipeline=pipeline)

    prompt = PromptTemplate(template=template, input_variables=["question","context"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    response = llm_chain.run({"question":question,"context":context})

    return response

# Example usage:
question_p = "What is the date for announcement"
context_p = "On August 10 said that its arm JSW Neo Energy has agreed to buy a portfolio of 1753 mega watt renewable energy generation capacity from Mytrah Energy India Pvt Ltd for Rs 10,530 crore."

response = generate_response(question_p, context_p)
print(response)

"""# Gradio"""

import os
import requests

def download_images(image_urls, output_dir):
    # Create the output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    for i, url in enumerate(image_urls):
        try:
            response = requests.get(url)
            if response.status_code == 200:
                with open(os.path.join(output_dir, f"image_{i+1}.jpg"), 'wb') as f:
                    f.write(response.content)
                print(f"Image {i+1} downloaded successfully.")
            else:
                print(f"Failed to download image {i+1}. Status code: {response.status_code}")
        except Exception as e:
            print(f"Error downloading image {i+1}: {e}")

if __name__ == "__main__":
    # List of image URLs to download
    image_urls = [
        "https://d1avenlh0i1xmr.cloudfront.net/df06b68a-e1a4-40a2-9504-42c0d9cdbaac/8-real-bill-of-restraunt-with-gst.jpg",
        "https://i0.wp.com/yummraj.com/wp-content/uploads/2015/11/img_0722.jpg?ssl=1",
        "https://pbs.twimg.com/media/Ec0d9Z_U8AAOZ6c.jpg:large",
    ]

    # Output directory
    output_directory = "examples"

    download_images(image_urls, output_directory)

from pdf2image import convert_from_path
import fitz

def gradio_output(uploaded_file):

  # Process based on file type
  allowed_extensions = ['.jpg', '.jpeg', '.png']
  if any(ext in uploaded_file for ext in allowed_extensions):
      image = Image.open(uploaded_file)
  elif '.pdf' in uploaded_file:
      # Convert first page of PDF to image
      pdf_document = fitz.open(uploaded_file)

      # Get the first page
      first_page = pdf_document[0]

      # Render the first page as an image
      image = first_page.get_pixmap()

      # Convert the image to Pillow Image
      image = Image.frombytes("RGB", [image.width, image.height], image.samples)

  else:
      return "Unsupported file format", None

  if image.mode == 'RGBA':
        image = image.convert('RGB')

  image_path = "uploaded_image.jpg"
  image.save(image_path)

  extracted_text = process_receipt_image("/content/GroundingDINO/uploaded_image.jpg")

  question = """Provide the invoice data in json format
  (NOTE: Only provide answer as JSON nothing else, also there might be spelling mistakes and data extracted from
  invoice could be raw and there might be some mistakes in understanding the data but your job is to intelligently
  indentify and fill in according to your understanding)
  """

  context = f"""
  Extracted Invoice data:

  {extracted_text}
  """

  response = generate_response(question, context)

  return response, Image.open("/content/GroundingDINO/boxes_image.jpg")

print(gradio_output("/content/GroundingDINO/data/receipt.jpg"))

demo = gr.Interface(
    gradio_output,
    inputs= gr.File(label="Upload your file"),
    outputs=["textbox", "image"],
    examples=[os.path.join("examples", f) for f in os.listdir("examples")],
)

if __name__ == "__main__":
    demo.launch()

"""# Comments"""

# import os
# from groundingdino.util.inference import load_model, load_image, predict, annotate
# import supervision as sv

# HOME = os.getcwd()
# CONFIG = os.path.join('/content/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py')

# WEIGHTS_NAME = 'groundingdino_swint_ogc.pth'
# WEIGHTS_PATH = os.path.join('weights', WEIGHTS_NAME)

# model = load_model(CONFIG, WEIGHTS_PATH)

# IMAGE_NAME = 'receipt.jpg'
# IMAGE_PATH = os.path.join(HOME, 'data', IMAGE_NAME)

# TEXT_PROMPT = 'receipt'
# BOX_THRESHOLD = 0.35
# TEXT_THRESHOLD = 0.25

# image_source, image = load_image(IMAGE_PATH)

# boxes, logits, phrases = predict(
#     model=model,
#     image=image,
#     caption=TEXT_PROMPT,
#     box_threshold=BOX_THRESHOLD,
#     text_threshold=TEXT_THRESHOLD
# )

# annotated_frame = annotate(
#     image_source=image_source,
#     boxes=boxes,
#     logits=logits,
#     phrases=phrases
# )


# sv.plot_image(annotated_frame)

# h, w, _ = image_source.shape
# box = boxes[0] * torch.Tensor([w, h, w, h])
# box[:2] -= box[2:] / 2
# box[2:] += box[:2]
# x0, y0, x1, y1 = box.int().tolist()
# input_box = np.array([x0,y0,x1,y1])
# input_point = None
# input_label = None

# img = image_source

# MODEL_TYPE = 'vit_h'
# SAM_CHECKPOINT_PATH = os.path.join(os.getcwd(), 'checkpoints/sam_vit_h_4b8939.pth')

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# sam = sam_model_registry[MODEL_TYPE](checkpoint=SAM_CHECKPOINT_PATH).to(device=device)

# predictor = SamPredictor(sam)
# predictor.set_image(img)

# masks, scores, _ = predictor.predict(
#     point_coords=None,
#     point_labels=None,
#     box=input_box,
#     multimask_output=False
# )

# sv.plot_image(masks[0])

# mask = np.expand_dims(masks[0], axis=0)
# mask = mask.transpose(1,2,0)
# mask = np.array(mask*255).astype('uint8')
# mask = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)

# segmented_image = mask
# segmented_image = cv2.bitwise_or(segmented_image, mask)

# segmented_image = cv2.bitwise_and(segmented_image, img)

# segmented_image2 = cv2.cvtColor(segmented_image, cv2.COLOR_BGR2GRAY)
# ret, thresh = cv2.threshold(segmented_image2, 127, 255, 0)

# sv.plot_image(thresh)

# # Save the thresholded image
# cv2.imwrite('segmented_image.jpg', thresh)

# import cv2
# import numpy as np
# from skimage.filters import threshold_local

# def opencv_resize(image, ratio):
#     width = int(image.shape[1] * ratio)
#     height = int(image.shape[0] * ratio)
#     dim = (width, height)
#     return cv2.resize(image, dim, interpolation=cv2.INTER_AREA)

# def approximate_contour(contour):
#     peri = cv2.arcLength(contour, True)
#     return cv2.approxPolyDP(contour, 0.032 * peri, True)

# def get_receipt_contour(contours):
#     for c in contours:
#         approx = approximate_contour(c)
#         if len(approx) == 4:
#             return approx

# def wrap_perspective(img, rect):
#     (tl, tr, br, bl) = rect
#     maxWidth = max(int(np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))),
#                    int(np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))))
#     maxHeight = max(int(np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))),
#                     int(np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))))
#     dst = np.array([
#         [0, 0],
#         [maxWidth - 1, 0],
#         [maxWidth - 1, maxHeight - 1],
#         [0, maxHeight - 1]], dtype="float32")
#     M = cv2.getPerspectiveTransform(np.array([tl, tr, br, bl], dtype="float32"), dst)
#     warped = cv2.warpPerspective(img, M, (maxWidth, maxHeight))
#     return warped

# def contour_to_rect(contour, resize_ratio):
#     pts = contour.reshape(4, 2)
#     rect = np.zeros((4, 2), dtype="float32")
#     s = pts.sum(axis=1)
#     rect[0] = pts[np.argmin(s)]
#     rect[2] = pts[np.argmax(s)]
#     diff = np.diff(pts, axis=1)
#     rect[1] = pts[np.argmin(diff)]
#     rect[3] = pts[np.argmax(diff)]
#     return rect / resize_ratio

# def bw_scanner(image):
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     T = threshold_local(gray, 21, offset=5, method="gaussian")
#     return (gray > T).astype("uint8") * 255

# # Read the image
# image = cv2.imread("segmented_image.jpg")

# # Downscale image for easier handling
# resize_ratio = 500 / image.shape[0]
# original = image.copy()
# image = opencv_resize(image, resize_ratio)

# # Convert the image to grayscale
# gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# # Apply Gaussian blur to reduce noise
# blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# # Perform edge detection using Canny
# edges = cv2.Canny(blurred, 50, 150)

# # Find contours in the edge-detected image
# contours, _ = cv2.findContours(edges.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# # Get the largest contour
# receipt_contour = get_receipt_contour(contours)

# # Apply perspective transform to the receipt contour
# scanned = wrap_perspective(image.copy(), contour_to_rect(receipt_contour, resize_ratio))

# # Convert the scanned image to black and white
# scanned_bw = bw_scanner(scanned)

# # Display the scanned image
# plt.imshow(scanned_bw, cmap='gray')
# plt.axis('off')
# plt.show()

# # Save the scanned image
# cv2.imwrite('scanned.jpg', scanned_bw)

# image = cv2.imread("segmented_image.jpg")
# # Downscale image as finding receipt contour is more efficient on a small image
# resize_ratio = 500 / image.shape[0]
# original = image.copy()

# # Function to resize the image while maintaining aspect ratio
# def maintain_aspect_ratio_resize(image, width=None, height=None, inter=cv2.INTER_AREA):
#     dim = None
#     (h, w) = image.shape[:2]

#     if width is None and height is None:
#         return image

#     if width is None:
#         r = height / float(h)
#         dim = (int(w * r), height)
#     else:
#         r = width / float(w)
#         dim = (width, int(h * r))

#     # resize the image
#     resized = cv2.resize(image, dim, interpolation=inter)

#     # return the resized image
#     return resized

# # Resize image for easier handling
# resized_image = maintain_aspect_ratio_resize(image, width=500)

# # Convert the resized image to grayscale
# gray_image = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

# # Use Canny Edge Detection to find edges in the image
# edges = cv2.Canny(gray_image, 50, 150)

# # Find contours based on edges detected
# contours, hierarchy = cv2.findContours(edges.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# # Sort contours based on contour area and ignore small contours
# contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]

# # Function to approximate and validate a contour
# def validate_contour(c, min_ratio=0.5, max_ratio=1.5):
#     peri = cv2.arcLength(c, True)
#     approx = cv2.approxPolyDP(c, 0.02 * peri, True)
#     # Check if contour is a quadrilateral
#     if len(approx) == 4:
#         (x, y, w, h) = cv2.boundingRect(approx)
#         aspectRatio = w / float(h)
#         # Check if the contour aspect ratio is within a reasonable range
#         if aspectRatio >= min_ratio and aspectRatio <= max_ratio:
#             return approx
#     return None

# # Iterate over contours to find a valid receipt contour
# for c in contours:
#     rect = validate_contour(c)
#     if rect is not None:
#         break

# # If a valid contour is found, proceed with perspective transform
# if rect is not None:
#     # Draw the contour on the image
#     image_with_contour = cv2.drawContours(resized_image.copy(), [rect], -1, (0, 255, 0), 2)
#     plt.imshow(cv2.cvtColor(image_with_contour, cv2.COLOR_BGR2RGB))
#     plt.title('Image with Contour')
#     plt.axis('off')
#     plt.show()
# else:
#     print("No valid contour found.")

# # Perspective transform to obtain a top-down view of the receipt
# def order_points(pts):
#     # Initialize a list of coordinates that will be ordered such that:
#     # the first entry in the list is the top-left, the second entry is the top-right,
#     # the third is the bottom-right, and the fourth is the bottom-left
#     rect = np.zeros((4, 2), dtype="float32")

#     # The top-left point will have the smallest sum, whereas the bottom-right will have the largest sum
#     s = pts.sum(axis=1)
#     rect[0] = pts[np.argmin(s)]
#     rect[2] = pts[np.argmax(s)]

#     # The top-right point will have the smallest difference, whereas the bottom-left will have the largest difference
#     diff = np.diff(pts, axis=1)
#     rect[1] = pts[np.argmin(diff)]
#     rect[3] = pts[np.argmax(diff)]

#     return rect

# def four_point_transform(image, pts):
#     # Obtain a consistent order of the points and unpack them individually
#     rect = order_points(pts)
#     (tl, tr, br, bl) = rect

#     # Compute the width of the new image, which will be the maximum distance between bottom-right and bottom-left
#     # x-coordinates or the top-right and top-left x-coordinates
#     widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
#     widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
#     maxWidth = max(int(widthA), int(widthB))

#     # Compute the height of the new image, which will be the maximum distance between the top-right and bottom-right
#     # y-coordinates or the top-left and bottom-left y-coordinates
#     heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
#     heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
#     maxHeight = max(int(heightA), int(heightB))

#     # Construct the set of destination points to obtain a "birds eye view" (i.e., top-down view) of the image,
#     # again specifying points in the top-left, top-right, bottom-right, and bottom-left order
#     dst = np.array([
#         [0, 0],
#         [maxWidth - 1, 0],
#         [maxWidth - 1, maxHeight - 1],
#         [0, maxHeight - 1]], dtype="float32")

#     # Compute the perspective transform matrix and then apply it
#     M = cv2.getPerspectiveTransform(rect, dst)
#     warped = cv2.warpPerspective(image, M, (maxWidth, maxHeight))

#     # Return the warped image
#     return warped

# # Apply the four point transform to obtain a top-down view of the receipt
# warped = four_point_transform(resized_image, rect.reshape(4, 2))

# # Convert the warped image to grayscale, then threshold it to give it that 'black and white' paper effect
# warped = cv2.cvtColor(warped, cv2.COLOR_BGR2GRAY)
# T = threshold_local(warped, 11, offset=10, method="gaussian")
# warped = (warped > T).astype("uint8") * 255

# # Show the original and scanned images
# plt.figure(figsize=(10,10))
# plt.subplot(1, 2, 1)
# plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
# plt.title('Original Image')
# plt.axis('off')

# plt.subplot(1, 2, 2)
# plt.imshow(warped, cmap='gray')
# plt.title('Scanned Image')
# plt.axis('off')

# plt.show()

# def plot_gray(image):
#     plt.figure(figsize=(16,10))
#     return plt.imshow(image, cmap='Greys_r')

# def plot_rgb(image):
#     plt.figure(figsize=(16,10))
#     return plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

# file_name = "scanned.jpg"
# image = cv2.imread(file_name)
# plot_gray(image)

# d = pytesseract.image_to_data(image, output_type=Output.DICT)
# n_boxes = len(d['level'])
# boxes = cv2.cvtColor(image.copy(), cv2.COLOR_BGR2RGB)
# for i in range(n_boxes):
#     (x, y, w, h) = (d['left'][i], d['top'][i], d['width'][i], d['height'][i])
#     boxes = cv2.rectangle(boxes, (x, y), (x + w, y + h), (0, 255, 0), 2)

# plot_rgb(boxes)

# extracted_text = pytesseract.image_to_string(image)
# print(extracted_text)